spring.application.name=SpringBootJMS
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=chaitanya001c@gmail.com
spring.mail.password=hvhe mqtc mmle nohb
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
server.port=8090
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.info.env.enabled=true